### ISSUE TITLE
caffe2 seq2seq link does not exist

### ISSUE THREAD

**Issue by David-Levinthal** [jonsafari/nmt-list#18]
https://github.com/caffe2/caffe2/blob/master/caffe2/python/examples/seq2seq.py
this link generated 404

I found
https://github.com/caffe2/caffe2/tree/master/caffe2/python/models/seq2seq
I found
https://github.com/caffe2/caffe2/blob/master/caffe2/python/models/seq2seq/translate.py
but going up one level on this url (to seq2seq)
changes the url to
https://github.com/caffe2/caffe2/tree/master/caffe2/python/models/seq2seq
not sure exactly how this works..but the source suggests it is a translator..but I found no instructions on configuration on invocation.

**Comment by jonsafari** [comment]
Thanks for the notice! I've updated it to the directory, which will get people to the general area.
